### ISSUE TITLE
Thank you! 

### ISSUE THREAD

**Issue by SaltyCatNS** [cmtjk/LinkUpConnect#10]
Your solution works really well! It's definitely helped me after the LLU update. Thank you so much for addressing the update so quickly! 

You have helped me get my blood sugar back onto my watch, which helps me manage my blood sugar just much better.

I do apologize though if this is the wrong place to express my thanks. 

Once again, thank you. You are doing good work.

**Comment by cmtjk** [comment]
You're welcome! It's nothing special and far from a good app code wise. But I'm glad if it helps people beside me in their everyday lives.
Regarding the latest issue @alanruttenberg already did a great job providing me all required information to fix the app.
