### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by pooyaww** [cmtjk/LinkUpConnect#3]
Hi,
Thank you for developing this app. I am currently using that and it is perfect!
Can you please explain how I can build this app on a Linux machine?
I am not an android developer but maybe it is a good motivation for me to learn about Java and contribute.
Is it possible to build everything only with **gradle** and without android studio?

**Comment by cmtjk** [comment]
Hi,
you can use  `./gradlew assembleDebug` to get an debug APK or `./gradle assembleRelease` to get an unsigned APK.
If you want a signed APK you need to generate your own key and keystore and execute  `./gradlew assembleRelease -Pandroid.injected.signing.store.file=<keystore-file> -Pandroid.injected.signing.store.password=<keystore-password> -Pandroid.injected.signing.key.alias=<key-name> -Pandroid.injected.signing.key.password=<key-password>` or update you `build.gradle` respectively.
Artifacts will get stored in the `./build/outputs/apk/`.
