### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by infossk** [cmtjk/LinkUpConnect#5]
![Screenshot_2022-11-14-23-22-29-098-edit_com teamviewer teamviewer market mobile](https://user-images.githubusercontent.com/8257881/201780652-844e9d88-c4c3-4883-90b2-6f18152d7aab.jpg)

**Comment by Andy-Baker** [comment]
I have the same problem since 14.11.2022

**Comment by cmtjk** [comment]
Thanks for reporting.
I have the issue myself. Maybe they slightly changed their APIs.
I'll look into it asap.

**Comment by Andy-Baker** [comment]
Perhaps it helps :)
Look here: https://insulinclub.de/index.php?thread/33987-llu-client/&postID=671500#post671500
It' s because they are now sending gzip.

**Comment by cmtjk** [comment]
> Perhaps it helps :) Look here: https://insulinclub.de/index.php?thread/33987-llu-client/&postID=671500#post671500 It' s because they are now sending gzip.

Yeah, that's what I suspected after seeing the gibberish in the logs.
New version will be available in a few minutes.
