### ISSUE TITLE
Save my settings

### ISSUE THREAD

**Issue by robbless** [cmtjk/LinkUpConnect#9]
I'm too stupid, how do i confirm/save my settings? I only see the screen to enter the username and password. On this screen the only button to click is "Reset". How do i save?

**Comment by pooyaww** [comment]
@robbless Just turn on the switch near the "Forward to xDrip" checkbox.

**Comment by cmtjk** [comment]
Correct, settings will be saved automatically as soon as you start fetching your data.
![grafik](https://github.com/cmtjk/LinkUpConnect/assets/24757415/e2e1c9a4-6558-48d6-87b2-ed5c1a8654d7)
